spring.application.name=ai-meeting-assistant
ollama.base-url=http://localhost:11434

spring.datasource.url=jdbc:sqlite:meeting-notes.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true