spring.application.name=orcific-minutes
ollama.base-url=http://localhost:11434
ollama.embedding-model=nomic-embed-text

spring.datasource.url=jdbc:sqlite:meeting-notes.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

whisper.base-url=${WHISPER_BASE_URL:http://localhost:8001}
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

